export const SP_LISTS = {
  ROLES_APP: 'Roles_App',
  APROBADORES: 'Aprobadores',
  AREAS: 'Areas',
  CENTROS_COSTO: 'CentroCostos',
  PERFILES_CARGOS: 'PerfilesCargos',
  SOLICITUDES: 'Solicitudes',
  CANDIDATOS: 'Candidatos',
  PARTICIPACIONES: 'Participaciones',
  OFERTAS: 'Ofertas',
  KPI_OFERTAS: 'KPI_Ofertas',
  PLANTILLAS_DOCUMENTO: 'PlantillasDocumento',
  CONTRATOS: 'Contratos',
  CONTRATACIONES: 'Contrataciones',
} as const;